# docker-compose.yml
version: '3'

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=staff
      - DB_TYPE=postgresql+asyncpg
      - DB_PORT=5432
      - DB_HOST=db
      - MODULE_NAME=app_factory
      - APP_MODULE=main
      - WORKER_CLASS=aiohttp.GunicornWebWorker
      - PORT=8080
      - LOG_LEVEL=debug
  db:
    image: postgres:13
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=staff
      - DB_TYPE=posgresql
      - DB_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/

volumes:
  init_db:
  postgres_data:
